"""
One source of truth for prompts and help text.
"""

COVARIATES_CATALOG = [
    {
        "attr": "natural_age",
        "label": "Natural age (years)",
        "kind": "bool",
        "help": "current age or age at death",
    },
    {
        "attr": "age_at_last_event",
        "label": "Age at last EHR event",
        "kind": "bool",
        "help": "age at last diagnosis event (ICD or SNOMED) in EHR.",
    },
    {
        "attr": "sex_at_birth",
        "label": "Sex at birth",
        "kind": "bool",
        "help": "sex at birth",
    },
    {
        "attr": "ehr_length",
        "label": "EHR length (years observed)",
        "kind": "bool",
        "help": "EHR duration, in year, from first to last diagnosis code",
    },
    {
        "attr": "dx_code_occurrence_count",
        "label": "DX code occurrence count",
        "kind": "bool",
        "help": "counts the occurrences of diagnosis codes throughout EHR of each participant. For example: person 1 having R50 (fever) code on 5 different dates, R05 (cough) code on 3 different dates, and R05.1 (acute cough) code on 2 different dates, will have a dx_code_occurrence_count = 10.",
    },
    {
        "attr": "dx_condition_count",
        "label": "Distinct condition count",
        "kind": "bool",
        "help": "counts the number of unique conditions occurred throughout EHR of each participant. For example, for the same person 1 above, the dx_condition_count = 3 (R05 - cough, R05.1 - acute cough, R50 - fever).",
    },
    {
        "attr": "genetic_ancestry",
        "label": "Genetic ancestry (indicator)",
        "kind": "bool",
        "help": "returns string values of predicted ancestries, e.g., 'eur, 'afr', etc. These are only useful if user would like to filter data by genetic ancestries.",
    },
    {
        "attr": "first_n_pcs",
        "label": "Genetic PCs (first_n_pcs)",
        "kind": "int",
        "help": "retrieves first n genetic PC components from genetic PCA data generated by All of Us.",
    },
    {
        "attr": "drop_nulls",
        "label": "Drop rows with NULL covariates",
        "kind": "bool",
        "help": "remove rows containing null values in any column.",
    },
]